---
- name: Registry keys for Windows Update
  block:
  - name: AcceptTrustedPublisherCerts
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
      name: AcceptTrustedPublisherCerts
      data: "{{ win_update_AcceptTrustedPublisherCerts }}"
      type: dword

  - name: DisableWindowsUpdateAccess
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
      name: DisableWindowsUpdateAccess
      data: "{{ win_update_DisableWindowsUpdateAccess }}"
      type: dword

  - name: ElevateNonAdmins
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
      name: ElevateNonAdmins
      data: "{{ win_update_ElevateNonAdmins }}"
      type: dword

  - name: TargetGroup
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
      name: TargetGroup
      data: "{{ win_update_TargetGroup }}"
      type: string

  - name: TargetGroupEnabled
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
      name: TargetGroupEnabled
      data: "{{ win_update_TargetGroupEnabled }}"
      type: dword

  - name: WUServer
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
      name: WUServer
      data: "{{ win_update_WUServer }}"
      type: string

  - name: WUStatusServer
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
      name: WUStatusServer
      data: "{{ win_update_WUServer }}"
      type: string

- name: Registry keys for Automatic Update configuration options
  block:
  - name: AUOptions
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: AUOptions
      data: "{{ win_update_AUOptions }}"
      type: dword

  - name: AutoInstallMinorUpdates
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: AutoInstallMinorUpdates
      data: "{{ win_update_AutoInstallMinorUpdates }}"
      type: dword

  - name: DetectionFrequency
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: DetectionFrequency
      data: "{{ win_update_DetectionFrequency }}"
      type: dword

  - name: DetectionFrequencyEnabled
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: DetectionFrequencyEnabled
      data: "{{ win_update_DetectionFrequencyEnabled }}"
      type: dword

  - name: NoAutoRebootWithLoggedOnUsers
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: NoAutoRebootWithLoggedOnUsers
      data: "{{ win_update_NoAutoRebootWithLoggedOnUsers }}"
      type: dword

  - name: NoAutoUpdate
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: NoAutoUpdate
      data: "{{ win_update_NoAutoUpdate }}"
      type: dword

  - name: RebootRelaunchTimeout
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: RebootRelaunchTimeout
      data: "{{ win_update_RebootRelaunchTimeout }}"
      type: dword

  - name: RebootRelaunchTimeoutEnabled
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: RebootRelaunchTimeoutEnabled
      data: "{{ win_update_RebootRelaunchTimeoutEnabled }}"
      type: dword

  - name: RebootWarningTimeout
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: RebootWarningTimeout
      data: "{{ win_update_RebootWarningTimeout }}"
      type: dword

  - name: RebootWarningTimeoutEnabled
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: RebootWarningTimeoutEnabled
      data: "{{ win_update_RebootWarningTimeoutEnabled }}"
      type: dword

  - name: RescheduleWaitTime
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: RescheduleWaitTime
      data: "{{ win_update_RescheduleWaitTime }}"
      type: dword

  - name: RescheduleWaitTimeEnabled
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: RescheduleWaitTimeEnabled
      data: "{{ win_update_RescheduleWaitTimeEnabled }}"
      type: dword

  - name: ScheduledInstallDay
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: ScheduledInstallDay
      data: "{{ win_update_ScheduledInstallDay }}"
      type: dword

  - name: ScheduledInstallTime
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: ScheduledInstallTime
      data: "{{ win_update_ScheduledInstallTime }}"
      type: dword

  - name: UseWUServer
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: UseWUServer
      data: "{{ win_update_UseWUServer }}"
      type: dword
